In [55]:
import numpy as np
from einexpr import einexpr, einfunc

In [2]:
X = einexpr(np.array([[1, 2], [3, 4]]))
Y = einexpr(np.array([[5, 6], [7, 8]]))
a = einexpr(np.array([1,2]))
b = einexpr(np.array([3,4]))

# Dot product
x = a['i'] + b['i']
print(x[''])

# Outer product
x = a['i'] * b['j']
print(x['i j'])

# Matrix-vector multiplication
x = X['i j'] * a['j']
print(x['i'])

# Matrix-matrix multiplication
x = X['i j'] * Y['j k']
print(x['i, k'])

# Linear transformation
@einfunc
def linear(x, W, b):
    return x['i'] * W['i j'] + b['j']

x_transformed = linear(x=np.array([1,2]), W=np.array([[1,2],[3,4]]), b=np.array([5,6]))
print(x_transformed['j'])

10[]
array([[3, 4],
       [6, 8]])['i', 'j']
array([ 5, 11])['i']
array([[19, 22],
       [43, 50]])['i', 'k']
array([17, 22])['j']


In [3]:
import jax.numpy as jnp

jnp.ones((10,10)).__array__()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [4]:
np.ndarray((), np.int64)

array(4652007308841189376)

In [54]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
a = np.array([1,2])
b = np.array([3,4])

Xe = einexpr(X)
Ye = einexpr(Y)
ae = einexpr(a)
be = einexpr(b)

# MULTIPLICATION
# np.einsum
print(np.einsum('ij,jk->ik', X, Y))

# the same thing in einexpr
print((Xe['i j'] * Ye['j k'])['i k'])

# ADDITION
# np.einsum
print(np.sum(X[:, :, np.newaxis] + Y[np.newaxis, :, :], axis=1))

# einexpr
print((Xe['i j'] + Ye['j k'])['i k'])

# LINEAR TRANSFORMATION
def linear(x, W, b):
    return np.einsum("i,ij->j", x, W) + b

print(linear(a, X, b))

@einfunc
def linear(x, W, b):
    return x['i'] * W['i j'] + b['j']

print(linear(a, X, b)['j'])

print((ae['i'] * Xe['i j'] + be['j']).coerce_into_shape('j'))

[[19 22]
 [43 50]]
array([[19, 22],
       [43, 50]])['i', 'k']
[[15 17]
 [19 21]]
array([[15, 17],
       [19, 21]])['i', 'k']
[10 14]
array([13, 18])['j']
__add__(Shaped(EinSum('i,ij->', [Shaped(array([1, 2]), (Index('i'),)), Shaped(array([[1, 2],
       [3, 4]]), (Index('i'), Index('j')))]), ()), Shaped(EinSum('j,->', [Shaped(array([3, 4]), (Index('j'),)), IndexSize(i)]), ()))[]


In [6]:
einexpr(np.array(einexpr(X)))

ndarray([[1 2]
 [3 4]], int64)

In [7]:
einexpr(X)

ndarray([[1 2]
 [3 4]], int64)

In [65]:
import einexpr